#!/bin/bash

source app-build/tools/_functions

set -e

export COMPOSE_FILE="docker-compose-production.yml"

cd app-build

heading "Pulling Docker images"
docker-compose pull >/dev/null

tools/env_check production

cd ../

if [[ -d app ]]; then

	cd app

	heading "Removing data"
	docker-compose -f docker-compose-tools.yml run --rm data rm -rf /data/src

	tools/stop production

	cd ../

fi

heading "Copying files"

rm -rf app && cp -r app-build app && echo "done"

cd app

tools/start

echo ""
